From Gaddis Chapter 11

---------------------------------------------
(50 pts)
Part I
Multiple Choice Questions (Gaddis p746-748) 
Questions 1-15
---------------------------------------------

1) When an exception is, generated it is said to have been  _____ .

answer: b , thrown

2) This is a section of code that gracefully responds to exceptions.

answer: c, exception handler

3) If you code does not handle an exception whent its thrown, its dealt with by this .

answer a, default exception handler

4) All exception class inherit from this class.

answer d, Throwable

5) FileNotFoundException inherits from 

answer b, IOException

6) You can think of this code being protected because the application will not halt if
it throws an exception.

answer a, try block 

7) This method can be used to retrieve an error message from an exception object.

answer d , getMessage

8) The numeric wrapper classes "parse" methods all throw an exception of this type


answer b, NumberFormatException 


9) This is one or more statements that are always executed after the try block has
executed and after any catch blocks have executed if an exception was throw.

answer c, finally block

10) This is an internal list of all the methods that are currently executing 

answer b, call stack

11) This method may be called from any exception object and it shows the chain of methods 
that were called when the exception was thrown

answer c, printStackTrace

12) These are exceptions that inherit from the Error class or the RunTimeException class .

answer b, unchecked exceptions

13) All exceptions that do not inherit from Error class or RunTimeException class are ___

answer d, checked exceptions 

14) This informs the compilier of the exceptions that could get thrown from a method.

answer a, throws clause

15) You use this statement to throw an exception manually.

answer c, throw

------------------------------------------------
Algorithmic Workbench Question 1 (Gaddis Chapter 11 page 750)
------------------------------------------------

1) What is the output of the following program?

public class ExceptionTest
{
   public static void main( String []  args ) {
      int number;
      String str;

      try {
         str = "XYZ";
	 number = Integer.parseInt(str);
         System.out.println("A");
      }
      catch( NumberFormatException e ) {
        System.out.println("B");
      }
      catch( IllegalArgumentException e ) {
        System.out.println("C");
      }
      System.out.println("D");
   }
}



Answer : the output will be

B
D

why :

Integer.parseInt("XYZ");

throws a NUmberFormatException


------------------------------------------------
Algorithmic Workbench Question 2 (Gaddis Chapter 11 page 750)
------------------------------------------------
1) What is the output of the following program?

public class ExceptionTest
{
   public static void main( String []  args ) {
      int number;
      String str;

      try {
         str = "XYZ";
	 number = Integer.parseInt(str);
         System.out.println("A");
      }
      catch( NumberFormatException e ) {
        System.out.println("B");
      }
      catch( IllegalArgumentException e ) {
        System.out.println("C");
      }
      finally {
        System.out.println("D");
      }
      System.out.println("E");
   }
}


answer:
B
D
E
   
